version: "3.9"

services:
    php:
        build:
            context: .
            args:
                LINUX_USER_ID: ${LINUX_USER_ID:-1000}
        container_name: signal-php
        volumes:
            - ./:/srv/app
